### ISSUE TITLE
Infografia Realidad Aumentada 

### ISSUE THREAD

**Issue by ObedG** [SistemasTecTlaxiaco/infografia-ObedG#1]
Esta infografía con tiene información que ayuda a conocer y comprender el concepto de realidad aumentada 

![Infografía comercial de las mejores aplicaciones de salud ilustrativa](https://user-images.githubusercontent.com/65927298/109891618-fedb2480-7c4e-11eb-96ef-980e00ea221b.png)

**Comment by AxayacatlS** [comment]
Calificacion 20

**Comment by josealfredo79** [comment]
Esta bien realizado y revisado
